let text = "<h1><b>TABEL PERKALIAN</b></h1>"
const num1 = 1;
const num2 = 2;
const num3 = 3;
const num4 = 4;
const num5 = 5;
const num6 = 6;
const num7 = 7;
const num8 = 8;
const num9 = 9;

document.writeln(text)
document.writeln("<br>1 x 1 = ", num1 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","1 x 2 = ", num1 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "1 x 3 = ", num1 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "1 x 4 = ", num1 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "1 x 5 = ", num1 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "1 x 6 = ", num1 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "1 x 7 = ", num1 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "1 x 8 = ", num1 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "1 x 9 = ", num1 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )
document.writeln("<br>2 x 1 = ", num2 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","2 x 2 = ", num2 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 3 = ", num2 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 4 = ", num2 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 5 = ", num2 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 6 = ", num2 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 7 = ", num2 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 8 = ", num2 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 9 = ", num2 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )
document.writeln("<br>3 x 1 = ", num3 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","3 x 2 = ", num3 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "3 x 3 = ", num3 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "3 x 4 = ", num3 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp", "3 x 5 = ", num3 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp", "3 x 6 = ", num3 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp", "3 x 7 = ", num3 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp", "3 x 8 = ", num3 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp", "3 x 9 = ", num3 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )
document.writeln("<br>4 x 1 = ", num4 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","4 x 2 = ", num4 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp", "4 x 3 = ", num4 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp", "4 x 4 = ", num4 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp", "4 x 5 = ", num4 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp", "4 x 6 = ", num4 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 7 = ", num2 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 8 = ", num2 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp", "4 x 9 = ", num4 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )
document.writeln("<br>5 x 1 = ", num5 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","5 x 2 = ", num5 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp", "5 x 3 = ", num5 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp", "5 x 4 = ", num5 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp", "5 x 5 = ", num5 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp", "5 x 6 = ", num5 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 7 = ", num2 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 8 = ", num2 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp", "5 x 9 = ", num5 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )
document.writeln("<br>6 x 1 = ", num6 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","6 x 2 = ", num6 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp", "6 x 3 = ", num6 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp", "6 x 4 = ", num6 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp", "6 x 5 = ", num6 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp", "6 x 6 = ", num6 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 7 = ", num2 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 8 = ", num2 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp", "6 x 9 = ", num6 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )
document.writeln("<br>7 x 1 = ", num7 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","7 x 2 = ", num7 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp", "7 x 3 = ", num7 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp", "7 x 4 = ", num7 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp", "7 x 5 = ", num7 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp", "7 x 6 = ", num7 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 7 = ", num2 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 8 = ", num2 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp", "7 x 9 = ", num7 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )
document.writeln("<br>8 x 1 = ", num8 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","8 x 2 = ", num8 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp", "8 x 3 = ", num8 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp", "8 x 4 = ", num8 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp", "8 x 5 = ", num8 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp", "8 x 6 = ", num8 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 7 = ", num2 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 8 = ", num2 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp", "8 x 9 = ", num8 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )
document.writeln("<br>9 x 1 = ", num9 * num1,"&nbsp&nbsp&nbsp&nbsp&nbsp","9 x 2 = ", num9 * num2,"&nbsp&nbsp&nbsp&nbsp&nbsp", "9 x 3 = ", num9 * num3,"&nbsp&nbsp&nbsp&nbsp&nbsp", "9 x 4 = ", num9 * num4,"&nbsp&nbsp&nbsp&nbsp&nbsp", "9 x 5 = ", num9 * num5,"&nbsp&nbsp&nbsp&nbsp&nbsp", "9 x 6 = ", num9 * num6,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 7 = ", num2 * num7,"&nbsp&nbsp&nbsp&nbsp&nbsp", "2 x 8 = ", num2 * num8,"&nbsp&nbsp&nbsp&nbsp&nbsp", "9 x 9 = ", num9 * num9,"&nbsp&nbsp&nbsp&nbsp&nbsp", )